### ISSUE TITLE
Avy's in Chat Boxes

### ISSUE THREAD

**Issue by MiteyDrill** [levimeahan/shinobi-chronicles#1]
Reading username on Chat Boxes is great, but I would like to have a small thumbnail in Chat Boxes to help visually differentiate each user 

Something like  
![image](https://user-images.githubusercontent.com/18477656/132157482-ac2c9fb7-c456-44f0-b2c2-93f90cf7afe3.png)

**Comment by MiteyDrill** [comment]
Placing this line of code **_after_** the **{switch statement} line 176** on **Chat.php** (The user name color switch) --- the code should implement the avy feature
                        
                        /*Cextra Zone*/
			$avyQuery = $system->query("SELECT `avatar_link` FROM `users` WHERE `user_name` = '$post[user_name]'");
			$avyLink = $system->db_fetch($avyQuery);

			echo
			"<img
			style='height: 50px;'
			src=\"".$avyLink['avatar_link']."\"
			/>".
			"<br/>";
			/*Cextra Zone*/

**Comment by levimeahan** [comment]
I like this idea, but I think this position would cause the chat rows to vertically stretch too much. How about if we put it to the left of everything else?

**Comment by levimeahan** [comment]
Merged in #2
