### ISSUE TITLE
[Medium] Add combat hotkeys

### ISSUE THREAD

**Issue by levimeahan** [levimeahan/shinobi-chronicles#10]
select jutsu, cast jutsu

**Comment by MiteyDrill** [comment]
Working on something that will work like hotkeys but it's only for the arena atm, can upload if you need

**Comment by levimeahan** [comment]
> 
> 
> Working on something that will work like hotkeys but it's only for the arena atm, can upload if you need

Sure, let's see it!

**Comment by MiteyDrill** [comment]
I literally just finished updating it, i'm trying to do a PR here, figuring out if I can do it thru this chat or not

**Comment by levimeahan** [comment]
> 
> 
> I literally just finished updating it, i'm trying to do a PR here, figuring out if I can do it thru this chat or not

You'll have to create it separately, but you can link this issue to it

**Comment by levimeahan** [comment]
https://github.com/levimeahan/shinobi-chronicles/pull/29#issuecomment-918704304

**Comment by MiteyDrill** [comment]
![image](https://user-images.githubusercontent.com/18477656/133305573-fac85d1f-f739-4b4f-b059-7e3016304712.png)
@levimeahan 

Just updated my Repo I believe it now displays hotkeys correctly by jutsu type as displayed. As long as the user doesn't own more than 10 of the same jutsu type. 

I've only been testing in Arena, not sure if this works in mission battles or pvp
