### ISSUE TITLE
Bug - Psychotic slash makes other taijutsu unable to select weapons

### ISSUE THREAD

**Issue by RandallJS** [levimeahan/shinobi-chronicles#101]
If you select Psychotic Slash from Demonic Weaponry bloodline then switch off to a taijutsu the weapon buttons do not function for the regular taijutsu techniques.

Steps to recreate:
Click on Psychotic Slash
Click on any other Taijutsu to change selection
Weapon buttons appear but do not work
Edit: Further testing shows interaction issue extends to hand signs for jutsu techniques as well. The images all appear but cannot be clicked on to change them. Jutsu handsign still works as intended so Jutsu are still usable.

Edit2: This issue seems to happen for me on firefox web browser but not on chrome on mobile at least, unsure about chrome on a PC.

Intended result:
Weapon buttons should appear with new, non blodline technique Taijutsu selection and be interactable.

Current Work-around:
Refresh of page resolves issue when it occurs.

**Comment by levimeahan** [comment]
Seems related to #79 , merging with that
