### ISSUE TITLE
Coloured handseals

### ISSUE THREAD

**Issue by ViscaBarre** [levimeahan/shinobi-chronicles#103]
Coloured versions for the twelve handseals currently in use. The .zip files include separate versions for Geisha and Shadow Ribbon layouts. If they are accepted for use, I can convert them to suit current Blue Scroll (and possibly Classic Blue if it's not obsolete). Is it possible to have each layout use a separate set?

[Geisha.zip](https://github.com/levimeahan/shinobi-chronicles/files/7268797/Geisha.zip)

[Shadow Ribbon.zip](https://github.com/levimeahan/shinobi-chronicles/files/7268799/Shadow.Ribbon.zip)

![Seal1_bird](https://user-images.githubusercontent.com/91370970/135657548-6d795976-47d5-4616-a619-f2d861171f91.png) ![Seal7_serpent](https://user-images.githubusercontent.com/91370970/135657606-cca7f04e-9944-463b-a29f-56860b173ac8.png) ![Seal10_monkey](https://user-images.githubusercontent.com/91370970/135657653-6f2c1dfa-0d58-4126-96f7-6f485d3aca27.png)

![Seal1_bird](https://user-images.githubusercontent.com/91370970/135657567-053bf63d-0821-4606-acbd-88b600c0ae95.png) ![Seal7_serpent](https://user-images.githubusercontent.com/91370970/135657699-58ac320a-a2ac-4e8d-864f-b633c3316747.png) ![Seal10_monkey](https://user-images.githubusercontent.com/91370970/135657715-1166f5bd-4433-42bb-9efc-92fb66310a37.png)

A little rough around the edges but. 🐱

**Comment by levimeahan** [comment]
Ooh I like this. We need to update the Battle UI to be more layout-configurable but then this is totally doable
