### ISSUE TITLE
Display pool cost visually while in combat + new health, chakra and stamina bars

### ISSUE THREAD

**Issue by ViscaBarre** [levimeahan/shinobi-chronicles#109]
### What?

Display how much of your chakra or stamina a move you've chosen to use will deplete.

- Choose an action to take in combat
- Before you hit submit button, the cost of the chosen action can be seen in your pool bars (see image below)

### Why

Currently you can't tell how much of your pools your chosen action will deplete. It isn't displayed through text, nor visuals. Even if it was displayed through text, maff is tuff. Displaying it visually would be one step towards more intuitive combat.

### Other

It was also mentioned the battle page needs new bar visuals for pools. The image is a screenshot from a Geisha rework underway, but it could be prototyped.

![image](https://user-images.githubusercontent.com/91370970/135728253-50679697-076f-4a62-8562-dd37c5bef320.png)

**Comment by HitoriWoB** [comment]
Love this idea. I feel visuals are sometimes easier than doing the calculations, especially if lag hits and you're on limited time frame.

**Comment by MiteyDrill** [comment]
![image](https://user-images.githubusercontent.com/18477656/135733949-2eab2568-c55c-44ca-a05b-5af3b0a628c4.png)
![image](https://user-images.githubusercontent.com/18477656/135733951-13650a81-7fc1-4282-a01a-10a312c5876e.png)
I got something working on my local, gonna publish as a branch => Arena_UI, someone can clone my branch if they want to see if they can finish it or expand on it

I just barely got it working for this one instance lol for ninjutsu 
[https://github.com/MiteyDrill/shinobi-chronicles/tree/Arena_UI](Arena_UI Branch)

**Comment by levimeahan** [comment]
Ooh nice, I've been planning to collapse the text into the healthbars, I like the idea of the pool cost preview too

**Comment by levimeahan** [comment]
Will fold this into combat update
