### ISSUE TITLE
Global Message [time posted]

### ISSUE THREAD

**Issue by MiteyDrill** [levimeahan/shinobi-chronicles#19]
![image](https://user-images.githubusercontent.com/18477656/132863668-f9956f19-e405-4d3d-84ce-3cf290214d15.png)

No clue at what time this message was posted, would be helpful if there was a recent date somewhere there.

**Comment by HitoriWoB** [comment]
I'll work on this.

**Comment by HitoriWoB** [comment]
Believe this can be closed as of commit on 9/28?
