### ISSUE TITLE
[Easy] User Journal [send message/report/send money] at bottom of user journals

### ISSUE THREAD

**Issue by MiteyDrill** [levimeahan/shinobi-chronicles#31]
![image](https://user-images.githubusercontent.com/18477656/133114419-61a35e79-5bf2-4360-ba5a-118c38b06ad1.png)

Not sure if this is intended.

**Comment by levimeahan** [comment]
Hmm I think we should leave report journal at the bottom, but move the rest above the journal

**Comment by MiteyDrill** [comment]
#45 New PR for this issue
