### ISSUE TITLE
[Bug, Maybe?] Gained BL Point When Using Regular Ninjutsu (Chakra Torrent) , intended?

### ISSUE THREAD

**Issue by coolingoreo** [levimeahan/shinobi-chronicles#53]
https://prnt.sc/1sqr6wg

**Comment by coolingoreo** [comment]
this time used a BL move and gained 1 Nin point.
http://prntscr.com/1sqrvs3

how to re-create: 

used chakra torrent (regular ninjutsu) on AI until 1 hit was left and finished him off with a BL move, gained 1 NIN instead of BL.

can be done vice-versa as well, use BL move until 1 hit left , finish off with regular ninjutsu and gain 1 BL.

interesting mechanic.

**Comment by SatoGojo** [comment]
Possibly could be due to using your highest level move which is ?Chakra Torrent? 

Currently what is known about the system is if you use nin moves more than your bl move, you will get a nin point and vice versa

**Comment by coolingoreo** [comment]
my bloodline move is my highest jutsu move, but this happens vice-versa as well.

even if i use default taijutsu move.

**Comment by levimeahan** [comment]
> Currently what is known about the system is if you use nin moves more than your bl move, you will get a nin point and vice versa
This is accurate, the system counts up the number of nin/tai/gen/BL jutsu you use and awards a point for whichever type you used the most throughout the fight. In the event of a tie (used two+ types the same) it will give a point to whatever your highest skill amount is (e.g. if ninjutsu skill is your highest stat)
