### ISSUE TITLE
Warning message after first logging in - User.php line 1204

### ISSUE THREAD

**Issue by levimeahan** [levimeahan/shinobi-chronicles#74]
Warning: count(): Parameter must be an array or
an object that implements Countable in
/var/www/vhosts/shinobichronicles.com/httpdocs/classes/User.php
on line 1204

https://github.com/levimeahan/shinobi-chronicles/blob/f2d5de82c1850305d85ac2c91c3f5f7764da86d1/classes/User.php#L1204

**Comment by HitoriWoB** [comment]
I believe the issue is the blacklist is a default of null, instead of an empty array upon registration. I'll do some quick testing to confirm.
