### ISSUE TITLE
[Minor Bug] Resetting to AS from a higher rank while training transfers the gains

### ISSUE THREAD

**Issue by ViscaBarre** [levimeahan/shinobi-chronicles#84]
- I set a Long training at Genin rank
- Went to reset my character to Akademi-sei
- Gained 24 gains instead of 16

Nothing major and likely part of an intentional process: if you set a training before a boost ends, you still receive the boosted gains even when the boost ends during it.

![Too high gains](https://user-images.githubusercontent.com/91370970/134784122-08f604e2-ae34-4542-99fb-840fbcc51498.png)

**Comment by levimeahan** [comment]
Hmmm. I think we could probably leave this as is - I'd rather be consistent about "gains are calculated at the start" or "gains are calculated at the end"
