### ISSUE TITLE
Stuck in exam despite resetting

### ISSUE THREAD

**Issue by FishRatio** [levimeahan/shinobi-chronicles#88]
I decided to reset my character in the middle of taking the Chuunin exams. Now I get the message "You cannot access this page during the exam!" when I go to the arena. The issue persists despite multiple resets.

**Comment by levimeahan** [comment]
What is your SC username?

**Comment by FishRatio** [comment]
Acheron

**Comment by levimeahan** [comment]
Fixed, sorry for inconvenience - I added 20 Ancient Kunai to your account 🙏

**Comment by FishRatio** [comment]
Thank you very much!
