### ISSUE TITLE
Team page features/Changes 

### ISSUE THREAD

**Issue by SatoGojo** [levimeahan/shinobi-chronicles#97]
https://i.imgur.com/Rd9AWWo.jpg
Basically allowing a team "signature banner" as a 2:1 ratio, moving mission details down to the mission tab, putting mission tab above team controls

Adding a hyperlink to profile page and team village page for said team 
For reference: 
https://i.imgur.com/mzHgYJR.jpg <- View profile page
https://i.imgur.com/oiGPuFx.jpg <- Village HQ Clan/Team page
Those hyperlinks would lead to showing team details: https://i.imgur.com/YniTE0u.png

**Comment by levimeahan** [comment]
I like this idea

**Comment by MiteyDrill** [comment]
I also like these ideas
